services:
    php:
        image: php56-apache:latest
        volumes:
            - ./src:/var/www/html
        networks:
            - development
        depends_on:
            -   mysql

    mysql:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: baduy_bis
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        networks:
            development:
                aliases:
                    - mysql
        volumes:
            - './data/mysql:/var/lib/mysql'
    
    adminer:
        image: adminer
        ports:
            - "8080:8080"
        networks:
            - development

networks:
    development:
        name: npm_portainer
        external: true
