services:
    php:
        image: php56-apache:latest
        container_name: bis-app
        volumes:
            - ./src:/var/www/html
        networks:
            - development
        depends_on:
            -   mysql

    mysql:
        image: mysql:5.6
        container_name: bis.mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: baduy_bis
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        networks:
            - development
        volumes:
            - './data/mysql:/var/lib/mysql'
    
    adminer:
        image: adminer
        ports:
            - "8080:8080"
        networks:
            - development

networks:
    development:
        name: development
        external: true
